services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db

  ollama:
    image: ollama/ollama:latest
    container_name: ollama
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama

  butterfly:
    build: .
    container_name: butterfly
    ports:
      - "5005:5005"
    environment:
      - OLLAMA_HOST=ollama
      - MONGODB_URI=mongodb://mongodb:27017
    depends_on:
      - mongodb
      - ollama
    volumes:
      - ./data:/app/data

volumes:
  mongodb_data:
  ollama_data:
